version: '2'

services:
    app:
      image: rtorralba/php7-with-db-extensions
      working_dir: /var/www
      command: php -S 0.0.0.0:8080 -t public
      ports:
        - 8080:8080
      volumes:
        - .:/var/www
      links:
          - db
    db:
      image: mysql
      restart: always
      ports:
        - "3307:3306"
      environment:
        - MYSQL_DATABASE=lpf
        - MYSQL_USER=dev
        - MYSQL_PASSWORD=password
        - MYSQL_ROOT_PASSWORD=password
      volumes:
          - mysqldata:/var/lib/mysql
          - ./docker-db-init.sql:/docker-entrypoint-initdb.d/init.sql
    e2e:
      image: cypress
      links:
        - app:lpf.local
      depends_on:
        - app
      environment:
        - CYPRESS_baseUrl=http://lpf.local:8080
        - DISPLAY=unix${DISPLAY}
      command: tail -f /dev/null
      volumes:
        - ./e2e/cypress:/app/cypress
        - ./e2e/cypress.json:/app/cypress.json
        - /dev/shm:/dev/shm
        - /tmp/.X11-unix:/tmp/.X11-unix

volumes:
    logs:
      driver: local
    mysqldata:
      driver: local
